apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hello-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-hello-app
  template:
    metadata:
      labels:
        app: flask-hello-app
    spec:
      containers:
      - name: flask-hello-app
        image: your-docker-username/flask-hello-app:1.0
        ports:
        - containerPort: 5000  

---
apiVersion: v1
kind: Service
metadata:
  name: flask-hello-app-service
spec:
  selector:
    app: flask-hello-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP